name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Environment setup
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: pip
      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_dev.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install dev dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install -r requirements_dev.txt
      - name: Run Black formatter check
        run: |
          curl https://raw.githubusercontent.com/gao-hongnan/common-utils/main/scripts/devops/ci_formatter.sh \
          | bash
      - name: Run Pylint check
        run: |
          curl -o \
          ci_linter.sh \
          https://raw.githubusercontent.com/gao-hongnan/common-utils/main/scripts/devops/ci_linter.sh && \
          bash ci_linter.sh pipeline-feature
