name: CD/CD for the ml-pipeline that builds all the pipeline modules and pushes them to the private PyPI registry. From where Airflow will install the latest versions and use them in the next run.

on:
  push:
    paths-ignore:
      - 'app-api/'
      - 'app-frontend/'
      - '**/*.yml'
      - '**/*.md'
    branches: [ "main" ]

env:
  CLOUDSDK_CORE_PROJECT: '${{ vars.MLOPS_PIPELINE_V1_INSTANCE_PROJECT }}'
  USER: '${{ vars.MLOPS_PIPELINE_V1_INSTANCE_USER }}'
  INSTANCE_NAME: '${{ vars.MLOPS_PIPELINE_V1_INSTANCE_NAME }}'
  ZONE: '${{ vars.MLOPS_PIPELINE_V1_INSTANCE_ZONE }}'

jobs:
  cicd_airflow:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}'
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 34.143.176.217
          username: ${{ vars.MLOPS_PIPELINE_V1_INSTANCE_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            cd ~/mlops-pipeline-v1
            git pull
            cd pipeline-feature
            curl -o publish_package.sh https://raw.githubusercontent.com/gao-hongnan/common-utils/main/scripts/devops/ci/ci_publish_package.sh
            bash publish_package.sh -u __token__ -p ${{ secrets.PYPI_TOKEN }}
