name: CI/CD Airflow

# This workflow performs CI/CD for a machine learning pipeline.
# On each push to the 'main' branch (ignoring certain paths), it builds all pipeline modules and pushes them to a private PyPI registry.
# Airflow then installs the latest versions from this registry and uses them in its next run.

on:
  push:
    paths-ignore:
      - 'app-api/'
      - 'app-frontend/'
      - '**/*.yml'
      - '**/*.md'
      - '**/*.sh'
    branches: [ "main" ]

env:
  CLOUDSDK_CORE_PROJECT: '${{ vars.MLOPS_PIPELINE_V1_INSTANCE_PROJECT }}'
  USER: '${{ vars.MLOPS_PIPELINE_V1_INSTANCE_USER }}'
  INSTANCE_NAME: '${{ vars.MLOPS_PIPELINE_V1_INSTANCE_NAME }}'
  ZONE: '${{ vars.MLOPS_PIPELINE_V1_INSTANCE_ZONE }}'

jobs:
  cicd_airflow:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}'
      - id: 'compute-ssh'
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          project_id: '${{ env.CLOUDSDK_CORE_PROJECT }}'
          user: '${{ env.USER }}'
          instance_name: '${{ env.INSTANCE_NAME }}'
          zone: '${{ env.ZONE }}'
          ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
          command: >
            cd ~/mlops-pipeline-v1 &&
            git pull